services:
  - type: web
    name: senadizinet
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: CRON_SECRET
        value: SENADIZI_SECRET
